"""
Tests for centralized dashboard formatters.
"""

from datetime import UTC, datetime

from dashboard import formatters


def test_missing_numeric_and_timestamp_formatting_is_deterministic():
    assert formatters.text(None) == "-"
    assert formatters.text("") == "-"
    assert formatters.price(None) == "-"
    assert formatters.price(float("nan")) == "-"
    assert formatters.price(float("inf")) == "-"
    assert formatters.price(float("-inf")) == "-"
    assert formatters.price(True) == "-"
    assert formatters.price(False) == "-"
    assert formatters.price("100") == "-"
    assert formatters.price(0) == "0.00"
    assert formatters.price(100.125) == "100.12"
    assert formatters.price(-100.125) == "-100.12"
    assert formatters.ratio(None) == "-"
    assert formatters.ratio(float("nan")) == "-"
    assert formatters.ratio(float("inf")) == "-"
    assert formatters.ratio(float("-inf")) == "-"
    assert formatters.ratio(True) == "-"
    assert formatters.ratio(0) == "0.0000"
    assert formatters.ratio(2) == "2.0000"
    assert formatters.ratio(-2.5) == "-2.5000"
    assert formatters.timestamp(datetime(2026, 7, 12, 9, 15, tzinfo=UTC)).startswith("2026-07-12 09:15:00")


def test_semantic_status_kinds_are_stable():
    assert formatters.semantic_kind("Running") == "positive"
    assert formatters.semantic_kind("Ready") == "positive"
    assert formatters.semantic_kind("Healthy") == "positive"
    assert formatters.semantic_kind("Connected") == "positive"
    assert formatters.semantic_kind("Allow") == "positive"
    assert formatters.semantic_kind("Approved") == "positive"
    assert formatters.semantic_kind("Bullish") == "positive"
    assert formatters.semantic_kind("Profit") == "positive"
    assert formatters.semantic_kind("Suitable") == "positive"
    assert formatters.semantic_kind("Aligned") == "positive"
    assert formatters.semantic_kind("Stopped") == "neutral"
    assert formatters.semantic_kind("Waiting") == "neutral"
    assert formatters.semantic_kind("Created") == "neutral"
    assert formatters.semantic_kind("Neutral") == "neutral"
    assert formatters.semantic_kind("No Position") == "neutral"
    assert formatters.semantic_kind("None") == "neutral"
    assert formatters.semantic_kind("-") == "neutral"
    assert formatters.semantic_kind("Not Ready") == "warning"
    assert formatters.semantic_kind("Degraded") == "warning"
    assert formatters.semantic_kind("Starting") == "warning"
    assert formatters.semantic_kind("Stopping") == "warning"
    assert formatters.semantic_kind("Conflict") == "warning"
    assert formatters.semantic_kind("Partial") == "warning"
    assert formatters.semantic_kind("Recovery Pending") == "warning"
    assert formatters.semantic_kind("Error") == "negative"
    assert formatters.semantic_kind("Locked") == "negative"
    assert formatters.semantic_kind("Blocked") == "negative"
    assert formatters.semantic_kind("Rejected") == "negative"
    assert formatters.semantic_kind("Failed") == "negative"
    assert formatters.semantic_kind("Bearish") == "negative"
    assert formatters.semantic_kind("Loss") == "negative"
    assert formatters.semantic_kind("Disconnected") == "negative"
    assert formatters.semantic_kind("Not Suitable") == "negative"
    assert formatters.semantic_kind("ready-ish") == "neutral"
    assert formatters.semantic_kind("something new") == "neutral"
    assert formatters.pnl_kind(10.0) == "positive"
    assert formatters.pnl_kind(-1.0) == "negative"
    assert formatters.pnl_kind(0) == "neutral"
    assert formatters.pnl_kind(None) == "neutral"
    assert formatters.pnl_kind(float("nan")) == "neutral"
    assert formatters.pnl_kind(float("inf")) == "neutral"
    assert formatters.pnl_kind(float("-inf")) == "neutral"
    assert formatters.pnl_kind(True) == "neutral"


def test_semantic_status_normalizes_case_spaces_hyphens_and_underscores():
    assert formatters.semantic_kind(" blocked ") == "negative"
    assert formatters.semantic_kind("NOT_READY") == "warning"
    assert formatters.semantic_kind("not-ready") == "warning"
    assert formatters.semantic_kind("not ready") == "warning"
    assert formatters.semantic_kind(" recovery_pending ") == "warning"
    assert formatters.semantic_kind("recovery-pending") == "warning"
    assert formatters.semantic_kind("NO_POSITION") == "neutral"
    assert formatters.semantic_kind("no-position") == "neutral"
