"""
====================================================
Vision Trading OS
Application Settings
====================================================
"""

import os
from dotenv import load_dotenv

# Load .env
load_dotenv()


class Settings:

    # Zerodha
    ZERODHA_API_KEY = os.getenv("ZERODHA_API_KEY", "")
    ZERODHA_API_SECRET = os.getenv("ZERODHA_API_SECRET", "")
    ZERODHA_ACCESS_TOKEN = os.getenv("ZERODHA_ACCESS_TOKEN", "")

    # Trading
    BROKER = os.getenv("BROKER", "ZERODHA")
    ENV = os.getenv("ENV", "DEVELOPMENT")

    # Dashboard
    WATCHLIST = [
        "NIFTY",
        "BANKNIFTY",
        "SENSEX",
    ]

    TIMEFRAME = "5m"

    VOICE_ENABLED = True

    AI_ENABLED = True

    # Live Market Validation
    LIVE_VALIDATION_ENABLED = os.getenv("LIVE_VALIDATION_ENABLED", "false")
    LIVE_VALIDATION_MODE = os.getenv("LIVE_VALIDATION_MODE", "OFF")
    LIVE_VALIDATION_INSTRUMENTS = os.getenv("LIVE_VALIDATION_INSTRUMENTS", "NIFTY,BANKNIFTY,SENSEX")
    LIVE_VALIDATION_OUTPUT_DIR = os.getenv("LIVE_VALIDATION_OUTPUT_DIR", "logs/live_validation")
    LIVE_VALIDATION_TICK_STALE_SECONDS = os.getenv("LIVE_VALIDATION_TICK_STALE_SECONDS", "10")
    LIVE_VALIDATION_TICK_GAP_WARNING_SECONDS = os.getenv("LIVE_VALIDATION_TICK_GAP_WARNING_SECONDS", "30")
    LIVE_VALIDATION_TICK_GAP_CRITICAL_SECONDS = os.getenv("LIVE_VALIDATION_TICK_GAP_CRITICAL_SECONDS", "60")
    LIVE_VALIDATION_OPTION_CHAIN_STALE_SECONDS = os.getenv("LIVE_VALIDATION_OPTION_CHAIN_STALE_SECONDS", "60")
    LIVE_VALIDATION_COMPONENT_STALE_SECONDS = os.getenv("LIVE_VALIDATION_COMPONENT_STALE_SECONDS", "120")
    LIVE_VALIDATION_EVENT_LATENCY_WARNING_MS = os.getenv("LIVE_VALIDATION_EVENT_LATENCY_WARNING_MS", "500")
    LIVE_VALIDATION_EVENT_LATENCY_CRITICAL_MS = os.getenv("LIVE_VALIDATION_EVENT_LATENCY_CRITICAL_MS", "1500")
    LIVE_VALIDATION_MAX_RECENT_IDENTITIES = os.getenv("LIVE_VALIDATION_MAX_RECENT_IDENTITIES", "256")
    LIVE_VALIDATION_MAX_FINDINGS = os.getenv("LIVE_VALIDATION_MAX_FINDINGS", "512")
    LIVE_VALIDATION_MAX_LATENCY_SAMPLES = os.getenv("LIVE_VALIDATION_MAX_LATENCY_SAMPLES", "512")
    LIVE_VALIDATION_REQUIRED_COMPONENTS = os.getenv(
        "LIVE_VALIDATION_REQUIRED_COMPONENTS",
        "MARKET_DATA,CANDLE,PRICE_ACTION,OPTION_CHAIN,PAPER_TRADING,PERFORMANCE_ANALYTICS",
    )


settings = Settings()
